// I'm not boring ;)                                                        at least I hope not

/* 
1). TakeDamage
2). int (Integer)
3). 1
4). int health = 100;
    return health - damageAmount;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkxddxO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;lxd:,,:lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;xKOoc::;,;cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:lOxc;;;;;,,'';lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNKOOKNWKl:dxc;;,'........,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO0NMMMWNK00OOdc:,;:cclxkl;,,'........,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkco0WWNXK0Oxdl:,::;,''cOKo'..........;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c,:dKKXNNNX0kdlc::;;;,',;'.      ...'cxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,,,l0NNNXXK0Okkkkkdlc;''''....   ..'ccclOWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMM0c,';dXX0kdollodddxOKKKOl,...........:coxoxNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl,l0Odlccc:clllccdKNNX0l;:c:;,'....';lkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWX0O0xcldooxOOxoollllllxXWWXkocldkOkdc;,,;dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNXKXNXKd:d0KNXkdolcccoxdlkXNXOxddllx0KOdlloOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNXNWWNKOkdxKNNOoolcclokKOodk0XOx0KkdodkOkoldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXNWWN0OKWX0KXkool:;,';cokkxdk0OkKKxollodxddkKXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNXNNXOONMMWKOkooo,..';cc;cooloOOdol;,''';oddxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXXXKkONMMMW0xdoo:..,xk;...',',lx;.lc.  ..cdO0xdOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWK00kdKMMMMMNkdol::,,oc. ..:k00Oo;','..',cd0NNxcoONWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWKkxol0WMMMMW0ol:;oxxd;.,dolOXNXxdOOdoookXNWMNxccxXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMKxlc:o0WMMMWKdl:;;ld:..:c',oxdk000OxxkOXMMMMXxccdKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWOl::coOXNWWMWXO;.,;.....,;,.,lxdxOOk0XWMMMW0dlldXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNOlccox0KK0xddc'........'...;lodONNXNMMWWNKOxookNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWKkdd0NWMWx,'.............';lc;;coOKKKKKKK0kxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN0OKWWNNNo................'.....'o0KK0KK00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXK0kOXNNXXk,..........,,;;;;,... .lKNKO0KKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNXK00kOXWNK0x,........;cllllldkd;...:ONN00XXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNNXK0kxkXMXkxc. ......:lodxkxkKWW0:..,oxk00KNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNNNX0O0O0NMNOo'.   ....,cxKNX00KXMXl'',:coO0OKXNNXKXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNWNXK0KK0OOOkdc'..  .....,xNMNXOOXWK:..':coOKkxk000kk0XWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNXNNNXK0OO0OOkolodl,... ....;oKWWX00Xk;..',:dKWK0OkxxdookXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMN0OKNNX0k0NX00OdoONWXx:..  ..',cOX0xdkc'....;o0XXKNN0xolld0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXkdkKK0OXWN0kkxxONMWKd;.   ...'';:lokd,.....,clooxXMMXdcld0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXxodkOkKWMN0dlo0WMMNOl.   ........',;,......':clodONMNklldKWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNklodxOWMMWKdlkWMMWKd;..  .........',.......,cclxkkKMNkllkNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKolod0MMMMWK0NMMWXkc. ............','.. . .;cclooxKNKkokNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWkllo0MMMMWXKWWWXkoc. .............'..... .;llllodk00O0NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNOdlxXWMMMXO00Oxox0l.................... .xOolllloxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWXOxx0NWMWKxdod0NMk. ..........  .......,OWKdllllloxKNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXKKXNNWWNXNMW0:......................lXWX0xollllloKWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMW0:............'''.........lXMMWOc:c:'.lXMMMMMMMWNKKNMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c,'.........',,,',;'.......c0WMWk;..  .cxOOOOxol:;dNMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,,''....',,,'..','........lNMMMXx:.  .......':d0NMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:...,,,,,'',,,...'...'','....,OWMMMMNkc......'dKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo......',,;;,';odk0xllodxxc'.'.:0MMMMMMWKd:'..,OMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,........''.':kKXXXK0K0KKKOdc:''dNMMMMMMMMWKd:'cKMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.........'..cOXXXXX0O0O0K00kxl;.;OWMMMMMMMMMMNOx0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.........'.,xKXXXXX0kOkk00OOkxl,'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.........''.,d0XXXXX0Okxk00OOOkd:',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.........'''ckKXXXXXKOxox0OOOOOxl,.lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.........''.;xKXXXXXXKOdlxOOOOOOkd;.;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,........''.,dKXKKKXXXXOoldOOOkkkkd:.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;........',.'l0XXXKKKKKKklldxxxxkkkdc'.:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWk,........',''ckKXXXKKKKOxlcllooxkkkkxl,.,dNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWk,........','.;dOKKK0kddol:::cloxkkOkOxo;..:0MMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWk,.........,'.,lxOOOkxdol:,;cccclodkkOOko;..'xWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWO;.........,'.,cdkOOOkxo:;..':ccccclodkkkd;...cXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMK:.........,,.,:lxkOOkdlc,.. .,ccccclodkkkd:...,OMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNl.........','':coxkkdool;.    ':ccccclxOOkdc....dWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXOl'........','':cldxxddol:'     .;ccccclokOOxl'...,kNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWx,.........','';ccoxkxxolc,....  .':ccccldOOOxl,....,OWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNo'''''''..,,,.'ccldkkkxlc:'........:cccccokOOko,....,xWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMKc..',,,,,,;,..;cldkkkxolc,.........;cccccokOOkx;....,xWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM0;..'',,,,;,'.,ccoxkkkdlclodxxxxol:;:clcccoxOOOx;....:0WMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWOc'..''',;,.':clxkkkdlcldXMMMMMMMWKdcllcclxOOOx:..;dKWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNOxol:,,,'';clxOkkxocloOWMMMMMMMMNklllcclxOOOkc;dXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:,;cldOOkkolllxXMMMMMMMMMM0ollccldOOOkddKMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OkkxkO0Okdlloo0WMMMMMMMMMMKdllccldOOOkxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0OXXXXXXKOxolloxXMMMMMMMMMMMXxllcccdOOOkdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0OKXXXXXKOolllo0WMMMMMMMMMMMNxllccloO00kdkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMX0KXXXXXX0dllllkNMMMMMMMMMMMMNxllccloOK0koxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMW00XXXXXXKkocloxXMMMMMMMMMMMMMNxcllcldOKKkodKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMXOKXXXXXX0xlllo0WMMMMMMMMMMMMMNxllllld0K0kod0NMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMN00XXXXXXKOdlllo0WMMMMMMMMMMMMMXdlollld0K0kooONMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMKOKXXXXXX0kocllxXMMMMMMMMMMMMMMKdoolcld000xolkNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMW0OXXXXNXK0xlclo0WMMMMMMMMMMMMMM0ddolcld00OxllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXO0XXXXXXKkocccdXMMMMMMMMMMMMMMW0ddolclx00OxllxNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWKOKXXXXXX0dlcclOWMMMMMMMMMMMMMMWOddlccok0OOxlldKMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMN0OXXXXXXXOoccclOWMMMMMMMMMMMMMMWOoolccdOOOOdlcd0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXO0KKKXXXKOocccl0MMMMMMMMMMMMMMMNkoolcldkOOkdlcd0NMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMKk0KKKKKKKOdcccl0MMMMMMMMMMMMMMMXxolccldOOOkdlcdOXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWKk00000KK0Odlcco0MMMMMMMMMMMMMMMKdolcclxOOOkdlcoOXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0k00000000Oxlccl0MMMMMMMMMMMMMMMKdllccokOOOkolcokKWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0k00000000Okoccl0MMMMMMMMMMMMMMMKdlccldOOOOxoccld0NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNOkOOOOOOOOOkoccl0MMMMMMMMMMMMMMM0olcclxOOOOxlcccokXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNOkOOOOOOOOOOdccoKMMMMMMMMMMMMMMMOlcclokO0OkdlccclkXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNOkOOOOOO000OxccoKMMMMMMMMMMMMMMMOlcoxkO00OkocccclxXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXkOOO0000000OklcdXMMMMMMMMMMMMMMM0ollodxxkkxocccccdKMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXOOO00000000OkocxNMMMMMMMMMMMMMMMN0dc:cclollccccccdXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXkk00000kxdollcl0WMMMMMMMMMMMMMMMMKdlccoxxdolccccoKWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXkO0KKKKOkxxdlcdNMMMMMMMMMMMMMMMMMKdlcc:;;:c:ccclOWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMKkO0OOkxxdoccc:oO00KNWMMMMMMMMMMMMMXkl;...okl',lONMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0doc,'..'co:cdx0OOOKXNWWMMMMMMMMMMMWXx;. ';';xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNKk:.   .lldK0KKKKKKKKNMMMMMMMMMMMMMMXxc;ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.. ..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0OOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM




*/ 